---
title: "Spatial Epi HW 3"
author: "David"
date: "2/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install_packages, include=FALSE}

if (!isTRUE(requireNamespace("INLA", quietly = TRUE))) {
  install.packages("INLA", repos = c(getOption("repos"), 
          INLA = "https://inla.r-inla-download.org/R/stable"),
          dep=TRUE)
}


if (!require(SUMMER)) install.packages("SUMMER", repos = "http://cran.us.r-project.org")
if (!require(foreign)) install.packages("foreign", repos = "http://cran.us.r-project.org")
if (!require(haven)) install.packages("haven")
if (!require(rgdal)) install.packages("rgdal")
if (!require(maptools)) install.packages("maptools")
if (!require(sp)) install.packages("sp")
if (!require(spdep)) install.packages("spdep")
if (!require(SpatialEpi)) install.packages("SpatialEpi")
if (!require(RColorBrewer)) install.packages("RColorBrewer")
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(maps)) install.packages("maps")
if (!require(broom)) install.packages("broom")
if (!require(raster)) install.packages("raster")
if (!require(leaflet)) install.packages("leaflet")
if (!require(dplyr)) install.packages("dplyr")
if (!require(tidyverse)) install.packages("tidyverse")


```


```{r load_packages, include=FALSE}

rm(list=ls())
library(foreign)
library(haven)
library(INLA)
library(rgdal)
library(maptools)
library(sp)
library(spdep)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(maps)
library(broom)
library(raster)
library(leaflet)
library(dplyr)
library(tidyverse)
library(SUMMER)

```


```{r, eval=TRUE, results='hide', warning=FALSE, message=FALSE}

#Cancer data
link = "https://github.com/dmccoomes/Spatial_epi/raw/master/HW%203/Data/ohio_data_ascending_fips.txt"
ohio_canc <- read.table(url(link), header=TRUE)

#Map data
zip_oh_map <- "https://github.com/dmccoomes/Spatial_epi/raw/master/HW%203/Map%20data.zip"

#library(utils)
temp=tempfile()
download.file(zip_oh_map, temp)
unzip(temp)

(maps=list.files(pattern = 'shp'))

#ohmap <- readOGR(url(zip_oh_map),stringsAsFactors=F) 

#ohmap <- readOGR(dsn="C:\\Users\\dcoomes\\Documents\\GitHub\\Spatial_epi\\HW 3\\Data\\Map data", #layer="ohio_map")

#When using PC in office
ohmap <- readOGR(dsn="C:\\Users\\dcoomes\\Desktop\\Epi PhD\\Classes\\Spatial epi\\Map data", layer="ohio_map")

#ordering of regions is not the same among the data sets - how do we align these two?
summary(ohmap)
ohmap$CNTYIDFP00

#summary(ohio_canc)
#ohio_canc$fips
#View(ohio_canc)


```


```{r inla_graph_file}

nb.map <- poly2nb(ohmap)
nb2INLA("oh_graph", nb.map)

```



```{r inla_fit}

ohio_canc2 <- as.data.frame(ohio_canc)

#need to merge map and cancer data together
ohmap$fips <- as.numeric(as.character(ohmap$CNTYIDFP00))
ohmap <- ohmap[order(ohmap$fips),]
ohmap <- merge(ohmap,ohio_canc,by="fips")

nb.map <- poly2nb(ohmap)
nb2INLA("oh_graph", nb.map)


#pc.prec <- list(theta = list(prior = "pc.prec",
                #param = c(1, 0.05)))

formula <- deaths ~ 1 + 
       f(fips, model="bym2", graph="oh_graph", scale.model=T, constr=T, 
         hyper=list(phi=list(prior="pc", param=c(0.5, 0.5), initial=1), prec=list(prior="pc.prec",
         param=c(0.3,0.01), initial=5))) 

ohio.fit1 <- inla(formula, data=ohio_canc, family="poisson", E=county_level_E,
                  control.predictor=list(compute=TRUE))


ohio.fit1 <- inla(Counts ~ 1 + f(Region, model="bym2", graph="oh_graph", scale.model=T, constr=T,                       hyper=list(phi=list(prior="pc.prec", param=c(0.5, 0.5), initial=1),
                 prec=list(prior="pc.prec", param=c(0.3,0.01), initial=5))))


```

