---
title: "Spatial Epi - Final Project"
author: "David Coomes"
date: "January 27, 2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
```


```{r install_packages, include=FALSE}

if (!isTRUE(requireNamespace("INLA", quietly = TRUE))) {
  install.packages("INLA", repos = c(getOption("repos"), 
          INLA = "https://inla.r=inla-download.org/R/stable"),
          dep=TRUE)
}


if (!require(SUMMER)) install.packages("SUMMER", repos = "http://cran.us.r-project.org")
if (!require(foreign)) install.packages("foreign", repos = "http://cran.us.r-project.org")



#Can add more here if needed

```


```{r load_packages, include=FALSE}

rm(list=ls())
library(foreign)
library(haven)
#Having trouble installing INLA on pc in office
#install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
library(INLA)
library(rgdal)
library(maptools)
library(sp)
library(spdep)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(maps)
library(broom)
library(raster)
library(leaflet)
library(dplyr)
library(tidyverse)
library(SUMMER)

```

Starting with Ethiopia Wave 3

```{r load_EPAR_data}

#loading health data
link_3 = "https://github.com/dmccoomes/Spatial_epi/raw/master/Final%20project/Raw%20data/ESS%20Wave%203/Ethiopia%20Wave%203%20data/ETH_2015_ESS_v02_M_STATA8/Household/sect3_hh_w3.dta"

et_w3_anth <- read_dta(url(link_3))
# head(et_w3_anth)
# summary(et_w3_anth)
# View(et_w3_anth)

#keeping only those we need
keep_vars <- c("household_id2", "rural", "pw_w3", "individual_id2", "ea_id2", "saq01", "saq02", "saq03", "saq04", "saq05", "saq06", "saq07", "hh_s3q12_a", "hh_s3q20a", "hh_s3q20d", "hh_s3q20e", "hh_s3q21_a", "hh_s3q21_b", "hh_s3q21_c", "hh_s3q22", "hh_s3q23")    
et_w3_anth <- et_w3_anth[keep_vars]

#renaming variables
et_w3_anth <- et_w3_anth %>%
  rename(
    u_5 = hh_s3q12_a,
    diarrhea_2wk = hh_s3q20a,
    breastfed_yn = hh_s3q20e,
    birth_day = hh_s3q21_a,
    birth_month = hh_s3q21_b,
    birth_year = hh_s3q21_c,
    weight_kg = hh_s3q20e,
    height_cm = hh_s3q21_a
  )
  
#downloading cover sheet data
link_cover = "https://github.com/dmccoomes/Spatial_epi/raw/master/Final%20project/Raw%20data/ESS%20Wave%203/Ethiopia%20Wave%203%20data/ETH_2015_ESS_v02_M_STATA8/Household/sect_cover_hh_w3.dta"

et_w3_cover <- read_dta(url(link_cover))
# View(et_w3_cover)

et_w3_cover <- et_w3_cover %>%
  rename(
    int_day=hh_saq13_a,
    int_month=hh_saq13_b,
    int_year=hh_saq13_c
  )

#downloading section 1
link_1 = "https://github.com/dmccoomes/Spatial_epi/raw/master/Final%20project/Raw%20data/ESS%20Wave%203/Ethiopia%20Wave%203%20data/ETH_2015_ESS_v02_M_STATA8/Household/sect1_hh_w3.dta"
et_w3_hh <- read_dta(url(link_1))

#Merging household cover data with health data
et_w3_health <- merge(et_w3_anth, et_w3_cover, no.dups=TRUE)
#View(et_w3_health)

et_w3_health <- merge(et_w3_health, et_w3_hh, no.dups=TRUE)
summary(et_w3_health$hh_s1q04h)
 
#keeping only some variables
#keep_vars <- c("household_id2", "rural", "pw_w3", "individual_id2", "ea_id2", "saq01")

#subset - only keep children under 5
et_w3_data <- subset(et_w3_health, u_5==1)

#renaming variables
et_w3_data <- et_w3_data %>%
  rename(
    age=hh_s1q04h
  )

et_w3_data <- et_w3_data  %>%
  select(household_id2, rural, pw_w3, individual_id2, ea_id2, u_5, weight_kg, height_cm, birth_month, birth_year, age, int_day, int_month, int_year)

summary(et_w3_data$age)

colnames(et_w3_data)
summary(et_w3_data$age)

#keeping only those that report 

#Generating age using date of interview and year of birth
#et_w3_health$year <- et_w3_health$ et_w3_health$hh_saq13_c

```


