---
title: "Spatial HW 4"
author: "David Coomes"
date: "March 2, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, cache=TRUE, message=FALSE)
```



```{r load_packages, include=FALSE}

if (!require(spdep)) install.packages("spdep", repos = "http://cran.us.r-project.org")
if (!require(raster)) install.packages("raster", repos = "http://cran.us.r-project.org")
if (!require(leaflet)) install.packages("leaflet", repos = "http://cran.us.r-project.org")
if (!require(SUMMER)) install.packages("SUMMER", repos = "http://cran.us.r-project.org")



```


```{r install_packages, include=FALSE}

rm(list=ls())
library(haven)
library(INLA)
library(rgdal)
library(maptools)
library(sp)
library(spdep)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(maps)
library(broom)
library(raster)
library(leaflet)
library(dplyr)
library(SUMMER)


knitr::opts_chunk$set(echo = FALSE)

```

```{r install_packages, include=FALSE}

if (!isTRUE(requireNamespace("INLA", quietly = TRUE))) {
  install.packages("INLA", repos = c(getOption("repos"), 
          INLA = "https://inla.r-inla-download.org/R/stable"),
          dep=TRUE)
}


if (!require(SUMMER)) install.packages("SUMMER", repos = "http://cran.us.r-project.org")
if (!require(foreign)) install.packages("foreign", repos = "http://cran.us.r-project.org")
if (!require(haven)) install.packages("haven")
if (!require(rgeos)) install.packages("rgeos")
if (!require(rgdal)) install.packages("rgdal")
if (!require(maptools)) install.packages("maptools")
if (!require(sp)) install.packages("sp")
if (!require(spdep)) install.packages("spdep")
if (!require(SpatialEpi)) install.packages("SpatialEpi")
if (!require(RColorBrewer)) install.packages("RColorBrewer")
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(maps)) install.packages("maps")
if (!require(broom)) install.packages("broom")
if (!require(raster)) install.packages("raster")
if (!require(leaflet)) install.packages("leaflet")
if (!require(dplyr)) install.packages("dplyr")
if (!require(tidyverse)) install.packages("tidyverse")
if (!require(SUMMER)) install.packages("SUMMER")


```


```{r load_packages, include=FALSE}

rm(list=ls())
library(foreign)
library(haven)
library(INLA)
library(rgdal)
library(maptools)
library(sp)
library(spdep)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(maps)
library(broom)
library(raster)
library(leaflet)
library(dplyr)
library(tidyverse)
library(SUMMER)
library(rgeos)

```


```{r, eval=TRUE, results='hide', warning=FALSE, message=FALSE, include=FALSE}

#Cancer data

#using github
link = "https://github.com/dmccoomes/Spatial_epi/raw/master/HW%203/Data/ohio_2019_version.txt"
ohio_canc <- read.table(url(link), header=TRUE)

#pc in office
#ohmap <- readOGR(dsn="C:\\Users\\dcoomes\\Dropbox\\Classes\\Spatial modeling\\HW 3\\Data\\Map data", layer="ohio_map")

#laptop
ohmap <- readOGR(dsn="/Users/david/Documents/GitHub/Spatial_epi/HW 3/Map data", layer="ohio_map")

#computer in library
#ohmap <- readOGR(dsn="C:\\Users\\dcoomes\\Documents\\GitHub\\Spatial_epi\\HW 3\\Map data", layer="ohio_map")

#ordering of regions is not the same among the data sets - how do we align these two?
#summary(ohmap)
#ohmap$COUNTYFP00

#creating neighbor file
nb.map <- poly2nb(ohmap)



```


```{r}

set.seed(03022020)

```


### Question 1

```{r fit_poisson_morans}


col.W <- nb2listw(nb.map, style="W",zero.policy=TRUE)
col.B <- nb2listw(nb.map, style="B",zero.policy=TRUE)

# kappaval <- function(Obs, fitted, df) {
#   sum((Obs - fitted)^2/fitted)/df
# }

#fitting poisson model
quasip_mod <- glm(data=ohio_canc, Obs ~ 1, offset=log(Exp), family=quasipoisson())
sidsres <- residuals(quasip_mod, type="pearson")
moran.test(sidsres, col.W)



# kappaest <- kappaval(ohio_canc$Obs, mod$fitted, mod$df.resid)
# nMC <- 1000
# ncts <- length(ohio_canc$Exp)
# yMC <- matrix(rpois(n=nMC * ncts, lambda=ohio_canc$Exp),
#               nrow=ncts, ncol=nMC)
# kappaMC <- NULL
# for (i in 1:nMC){
#  modMC <- glm(yMC[,i]~1,offset=log(ohio_canc$Exp),family="quasipoisson")
#  kappaMC[i] <- kappaval(yMC[,i],modMC$fitted,modMC$df.resid)
# }

```


```{r fit_geary}

#add in latitude and longitude to run geary test
ohmap$fips <- as.numeric(as.character(ohmap$CNTYIDFP00))
#ordering fips so that counties align in data sets:
#ohmap <- ohmap[order(ohmap$fips),]            
ohio_canc2 <- merge(ohio_canc, ohmap, by.x="fips", by.y="fips")

ohio_canc2$lat <- as.character(as.numeric(ohio_canc2$INTPTLAT00))
ohio_canc2$lon <- as.character(as.numeric(ohio_canc2$INTPTLON00))

#fitting poisson model
quasip_mod2 <- glm(data=ohio_canc2, Obs ~ lat + lon, offset=log(Exp),
                  family=quasipoisson())
sidsres2 <- residuals(quasip_mod2, type="pearson")


geary.test(sidsres2,col.W)


```


```{r hist_kappa, include=FALSE}

#don't need this
hist(kappaMC, xlim=c(min(kappaMC),
          max(kappaMC, kappaest)), main="",
          xlab = expression(kappa))
abline(v=kappaest, col="red")

```



### Question 2

```{r}

library(SpatialEpi)
pop.upper.bound <- 20
n.simulations <- 1000
alpha.level <- 0.05

#need to create this - slide 39?
#geo <- latlong2grid(coordinates(ohmap))

getLabelPoint <- function(fips) {
  Polygon(fips[c("INTPTLON00", "INTPTLAT00")])@labpt
}

centOH <- by(ohmap, ohmap$fips, getLabelPoint)

Kpoisson <- kulldorff(geo, ohio_canc2$Obs, population=ohio_canc2$N,
                      expected.cases=NULL,
                      pop.upper.bound, n.simulations, alpha.level, plot=T)

            

```





### Question 3

```{r}

if (!require(geoR)) install.packages("geoR")
library(geoR)
data("ca20")
plot(ca20)

```


```{r}

cloudca <- variog(ca20, option="cloud")

```



