---
title: "Spatial Epi HW 2"
author: "David Coomes"
date: "2/5/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
```


```{r install_packages, include=FALSE}

rm(list=ls())
library(haven)
#install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
library(INLA)
library(rgdal)
library(maptools)
library(sp)
library(spdep)
library(SpatialEpi)
library(RColorBrewer)
library(ggplot2)
library(maps)
library(broom)
library(raster)
library(leaflet)
library(dplyr)

```


```{r load_data}

link = "https://github.com/dmccoomes/Spatial_epi/raw/master/HW%202/ohio_2019_version.txt"
ohio_canc <- read.table(url(link), header=TRUE)

#data
#Obs= observed deaths
#Exp = expected deaths

```


```{r map}

zip_ohmap_SHP = "https://github.com/dmccoomes/Spatial_epi/raw/master/HW%202/Ohio%20shape%20files%20(2).zip"

```


```{r, eval=TRUE}

library(utils)
temp=tempfile()
download.file(zip_ohmap_SHP, temp)
unzip(temp)

```


```{r}

#DMC - showing which tempfiles are in the directory

(maps=list.files(pattern = 'shp'))

```


```{r, eval=TRUE, results='hide', warning=FALSE, message=FALSE}
# notice the parameters use in the chunk!!

#ohMap <- readOGR("ohio_map.shp",stringsAsFactors=F) 

#On pc
ohio_map <- readOGR(dsn="/Users/david/Desktop/Dave/school/Spatial Epi/HW 2/HW 2_data", layer = "ohio_map")

#on laptop
#ohio_map <- readOGR(dsn="C:/Users/dcoomes/Documents/GitHub/Spatial_epi/HW 2/Ohio shape files", layer="ohio_map")


```


```{r smr}

#creating SMRs
ohio_canc$smr <- ohio_canc$Obs/ohio_canc$Exp

```


```{r merging_data}

ohio_map$fips <- as.numeric(as.character(ohio_map$CNTYIDFP00))
ohio_map <- merge(ohio_map,ohio_canc,by="fips")

```


```{r ggplot_map_obs}

#set breakpoints for plotting
num_bins <- 8
quants <- round(quantile(ohio_map@data$Obs, seq(0,1,length.out=num_bins)),2)
ohio_map@data$obs_cut <- cut(ohio_map@data$Obs, breaks=c(quants, Inf), include.lowest=TRUE, right=FALSE)

ohio_df <- tidy(ohio_map)

ohio_map$polyID <- sapply(slot(ohio_map, "polygons"), function(x) slot(x, "ID"))
ohio_df <- merge(ohio_df, ohio_map, by.x="id", by.y="polyID")

observed_ct_map <- ggplot() +
  geom_polygon(
    data=ohio_df,
    aes(x=long, y=lat, group=group,
        fill = obs_cut)) + 
  scale_fill_brewer("Observed deaths", palette="RdBu", direction=-1) +
  theme(line=element_blank(),
        axis.text=element_blank(),
        axis.title=element_blank()) + 
  coord_equal()

#save the map
ggsave("ohio_map_obs_ggplot.pdf", width=8, height=8)

plot(observed_ct_map,
     border='blue',
     lwd=1)

```



```{r ggplot_map_exp}

#set breakpoints for plotting
num_bins <- 8
quants <- round(quantile(ohio_map@data$Exp, seq(0,1,length.out=num_bins)),2)
ohio_map@data$exp_cut <- cut(ohio_map@data$Exp, breaks=c(quants, Inf), include.lowest=TRUE, right=FALSE)

ohio_df <- tidy(ohio_map)

ohio_map$polyID <- sapply(slot(ohio_map, "polygons"), function(x) slot(x, "ID"))
ohio_df <- merge(ohio_df, ohio_map, by.x="id", by.y="polyID")

expected_ct_map <- ggplot() +
  geom_polygon(
    data=ohio_df,
    aes(x=long, y=lat, group=group,
        fill = exp_cut)) + 
  scale_fill_brewer("Expected deaths", palette="RdBu", direction=-1) +
  theme(line=element_blank(),
        axis.text=element_blank(),
        axis.title=element_blank()) + 
  coord_equal()

#save the map
ggsave("ohio_map_exp_ggplot.pdf", width=8, height=8)

plot(expected_ct_map,
     border='blue',
     lwd=1)

```


```{r ggplot_map_smr}

#set breakpoints for plotting
num_bins <- 8
quants <- round(quantile(ohio_map@data$smr, seq(0,1,length.out=num_bins)),2)
ohio_map@data$smr_cut <- cut(ohio_map@data$smr, breaks=c(quants, Inf), include.lowest=TRUE, right=FALSE)

ohio_df <- tidy(ohio_map)

ohio_map$polyID <- sapply(slot(ohio_map, "polygons"), function(x) slot(x, "ID"))
ohio_df <- merge(ohio_df, ohio_map, by.x="id", by.y="polyID")

smr_ct_map <- ggplot() +
  geom_polygon(
    data=ohio_df,
    aes(x=long, y=lat, group=group,
        fill = smr_cut)) + 
  scale_fill_brewer("SMR", palette="RdBu", direction=-1) +
  theme(line=element_blank(),
        axis.text=element_blank(),
        axis.title=element_blank()) + 
  coord_equal()

#save the map
ggsave("ohio_map_smr_ggplot.pdf", width=8, height=8)

plot(smr_ct_map,
     border='blue',
     lwd=1)

```
